### ISSUE TITLE
cross-env NODE_ENV=development rollup -cw

### ISSUE THREAD

**Issue by akitengineer** [dangvanthanh/vue-ckeditor#2]
npm ERR! Linux 4.4.0-38-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v4.2.6
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! vue-ckeditor@1.0.0 dev: `cross-env NODE_ENV=development rollup -cw`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue-ckeditor@1.0.0 dev script 'cross-env NODE_ENV=development rollup -cw'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vue-ckeditor package,
npm ERR! not with npm itself.

**Comment by dangvanthanh** [comment]
@akitengineer What command line you use?

You need install package by

`npm install` or `yarn install` first

Then you can use `npm run dev` or `yarn run dev`

**Comment by akitengineer** [comment]
I used the commands in the same manner. npm install run successfully but npm run dev return the error.

I am using Ubuntu 16.04.

**Comment by dangvanthanh** [comment]
hi @akitengineer 

I'm running test in Ubuntu 16.10. It working well

[![asciicast](https://asciinema.org/a/d7z6h5k1s7yirl5kerl0l4iy2.png)](https://asciinema.org/a/d7z6h5k1s7yirl5kerl0l4iy2?autoplay=1)

Maybe you should upgrade Node.js package.

```
sudo apt-get update && sudo apt-get purge nodejs npm
```

**Comment by dangvanthanh** [comment]
I will closed it and reopen when you sure it a bug.
