### ISSUE TITLE
4.6 Support

### ISSUE THREAD

**Issue by wcarron27** [dangvanthanh/vue-ckeditor#6]
Hey, I'm looking to implement CKEDITOR in Vue.js2.x. I appreciate what you're doing. It's tremendously helpful. Just wondering the compatibility or plan for supporting the new v4.6.x of CKEDITOR.

**Comment by DominiqueFERET** [comment]
i have tested with this version this morning... seem to work on my project ... can you give a jsfiddle to see your problem ?

**Comment by dangvanthanh** [comment]
@wcarron27 I run code with bundle code in this reposity is working with Ckeditor 4.6. You can see [Vue 2 and Ckeditor 4.6](https://jsfiddle.net/dangvanthanh/168ofjwt/)

@DominiqueFERET Thank you for testing.

**Comment by wcarron27** [comment]
I actually managed to get it working with some fiddling. Thanks for being responsive. Cheers!
